language: node_js
node_js:
  - "11.14.0"

branches:
  only:
  - staging

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
script: gulp file_changes
